### ISSUE TITLE
Failed in a newly formatted Mac with Yosemite

### ISSUE THREAD

**Issue by dfleury** [tsuru/now#22]
Hi guys, I'm getting this error when running the install command. Take a look:

```
➜  ~  curl -sL https://raw.githubusercontent.com/tsuru/now/master/run.bash | bash
bash: line 35: wheezy: unbound variable
```

**Comment by dfleury** [comment]
I just saw the first line of README to notice that tsuru-now doesn't work on mac
```
Yet another script to install tsuru and its dependencies on Ubuntu or Debian distros.
```

Sorry about that...

**Comment by tarsisazevedo** [comment]
@dfleury you can use tsuru-bootstrap to create a VM running tsuru.
https://github.com/tsuru/tsuru-bootstrap

**Comment by dfleury** [comment]
Thanks! I can do a good use of that too.
