### ISSUE TITLE
bash: line 456: private_ip: unbound variable

### ISSUE THREAD

**Issue by PatrickSocha** [tsuru/now#30]
On running 'curl -sL https://raw.githubusercontent.com/tsuru/now/master/run.bash | bash -s -- --template server' the following error is returned before the script is fully executed:

```
Successfully installed python-swiftclient python-keystoneclient futures iso8601 stevedore oslo.utils pbr Babel netaddr oslo.serialization oslo.i18n oslo.config pytz debtcollector netifaces monotonic msgpack-python wrapt
Cleaning up...
bash: line 456: private_ip: unbound variable
```

This issue seems to stem from commit: 19cde8f8e16682eb73b6458ca014b03cfd3731b2

**Comment by morpheu** [comment]
Sorry about that. Commit already reverted.
