### ISSUE TITLE
Unable to install on a OpenVZ machine

### ISSUE THREAD

**Issue by diegoponciano** [tsuru/now#33]
I'm trying to install Tsuru on a Dacentec VPS, but it fails trying to install the package linux-image-extra:
```
E: Unable to locate package linux-image-extra-2.6.32-042stab108.8
E: Couldn't find any package by regex 'linux-image-extra-2.6.32-042stab108.8'
```
Any ideas how can I get past this step?

**Comment by magnotorres** [comment]
Which linux distribution and version are you using? Sounds like it is too old to run docker... We recommend to use ubuntu 14.04 LTS  (kernel 3.13, I believe the minimum version is 3.8)

**Comment by magnotorres** [comment]
@diegoponciano as VPS is an container and not a VM, it is not trivial to run docker on it. It only will work if the VPS is prepared to support it: https://openvz.org/Docker_inside_CT. Even in this case, the "tsuru now" would have some changes to work. The best/easy way to try tsuru is using a VM(ec2, vagrant) with ubuntu 14.04 LTS

**Comment by diegoponciano** [comment]
I'm using Ubuntu 15.04, and changing the line
```
sudo apt-get install linux-image-extra-$(uname -r) -qqy
```
to
```
sudo apt-get install linux-image-extra-virtual -qqy
```
allowed me to run the script almost to the end though.
Trying to install docker, it said my kernel version isn't supported, as you mentioned, so I'll switch to a KVM VPS instead.
Thanks!
