### ISSUE TITLE
DO install fails bash: line 411: tsuru_ppa_source: unbound variable

### ISSUE THREAD

**Issue by devekko** [tsuru/now#35]
second attempt of running bash NOW on DO

Setting up python-keystoneclient (1:0.7.1-ubuntu1.3) ...
Setting up python-swiftclient (1:2.0.3-0ubuntu1) ...
New target default -> not found:8080 added to target list
New target is default -> not found:8080
bash: export: `found:6060': not a valid identifier
Adding tsurud token to ~git/.bash_profile
Opening config file: /etc/tsuru/tsuru.conf
Done reading config file: /etc/tsuru/tsuru.conf
bash: export: `found:6060': not a valid identifier
Adding tsurud host to ~git/.bash_profile
Creating initial admin user...
bash: line 411: tsuru_ppa_source: unbound variable

**Comment by devekko** [comment]
tried running script locally and using source install of tsuru

    6  wget https://raw.githubusercontent.com/tsuru/now/master/run.bash
    7  chmod +x run.bash 
    8  ./run.bash --tsuru-from-source



New target default -> not found:8080 added to target list
New target is default -> not found:8080
bash: export: `found:6060': not a valid identifier
bash: export: `found:8080': not a valid identifier
bash: export: `found:6060': not a valid identifier
bash: export: `found:6060': not a valid identifier
bash: export: `found:8080': not a valid identifier
bash: export: `found:6060': not a valid identifier
Adding tsurud host to ~git/.bash_profile
Creating initial admin user...
./run.bash: line 411: tsuru_ppa_source: unbound variable

**Comment by fsouza** [comment]
Hi @devekko, thanks for reporting. This is due to recent changes in tsuru now. I have just pushed a fix.

**Comment by devekko** [comment]
please re-open

rebuilt DO image and ran script, same error

    1  curl -sL https://raw.githubusercontent.com/tsuru/now/master/run.bash | bash

New target default -> not found:8080 added to target list
New target is default -> not found:8080
bash: export: `found:6060': not a valid identifier
Adding tsurud token to ~git/.bash_profile
Opening config file: /etc/tsuru/tsuru.conf
Done reading config file: /etc/tsuru/tsuru.conf
bash: export: `found:6060': not a valid identifier
Adding tsurud host to ~git/.bash_profile
Creating initial admin user...
bash: line 411: tsuru_ppa_source: unbound variable

**Comment by devekko** [comment]
tried again running script locally, same error

    3* wget https://raw.githubusercontent.com/tsuru/now/master/run.bas
    4  chmod +x run.bash
    5  ./run.bash


The following packages were automatically installed and are no longer required:
  linux-headers-3.13.0-61 linux-headers-3.13.0-61-generic
  linux-image-3.13.0-61-generic linux-image-extra-3.13.0-61-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
New target default -> not found:8080 added to target list
New target is default -> not found:8080
bash: export: `found:6060': not a valid identifier
bash: export: `found:8080': not a valid identifier
bash: export: `found:6060': not a valid identifier
bash: export: `found:6060': not a valid identifier
bash: export: `found:8080': not a valid identifier
bash: export: `found:6060': not a valid identifier
Adding tsurud host to ~git/.bash_profile
Creating initial admin user...
./run.bash: line 411: tsuru_ppa_source: unbound variable
root@tsuru0:~#

**Comment by fsouza** [comment]
I will try to reproduce this on Digital Ocean. Thanks for reporting.

**Comment by fsouza** [comment]
There were two issues, and they're now fixed, I've just tested it on a DO box. Can you try again?

If you're not launching a new Droplet, please clean-up the file ~git/.bash_profile:

```
% > ~git/.bash_profile
```

Thanks for reporting the issue!

**Comment by devekko** [comment]
I guess, the installer works now

great thanks !

I am now at 

Welcome to tsuru!
tsuru is an open source PaaS, that aims to make it easier for developers to run their code in production.

Installing...................

**Comment by fsouza** [comment]
@devekko awesome, thanks for confirming!
