### ISSUE TITLE
SSL install error

### ISSUE THREAD

**Issue by devekko** [tsuru/now#37]
not sure if this is a false positive etc

just installing on KVM on Proxmox at OVH and gettint this during install of NOW

remote: Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
remote: Collecting Django==1.9 (from -r /home/application/current/requirements.txt (line 1))
remote: /home/application/.app_env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
remote:   InsecurePlatformWarning

**Comment by andrewsmedina** [comment]
it is happening on "tsuru-dashboard" deploy. It is only a warning from Python, not an error.

**Comment by ArxdSilva** [comment]
Hi @devekko we are deprecating now script in favor of [tsuru installer](https://docs.tsuru.io/stable/experimental/installer.html) (it's yet with experimental status in docs, but it's well tested and will be the recommended way soon)

Please try Tsuru Installer and let we now your impressions.
We have a [recent article about installing Tsuru with installer in google cloud platform](https://blog.tsuru.io/tsuru-paas-on-google-cloud-platform-21640abb4386)

If you want to run Tsuru in your mac without using VM, take a look at our [docker-compose.yml](https://github.com/tsuru/tsuru/blob/master/docker-compose.yml), it's used for dev environment but you can change to run Tsuru images directly. more info: https://docs.tsuru.io/master/contributing/index.html#development-environment
