### ISSUE TITLE
Error when try to install

### ISSUE THREAD

**Issue by fellipeh** [tsuru/now#44]
```
Writing objects: 100% (10691/10691), 10.06 MiB | 0 bytes/s, done.
Total 10691 (delta 6125), reused 10686 (delta 6121)
remote: HEAD is now at 7f5b36a... travis: configure email notifications
remote: You must provide a valid Authorization header
To git@172.31.15.180:tsuru-dashboard.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@172.31.15.180:tsuru-dashboard.git'
```

I'm on Amazon EC2, with Ubuntu 14.04 LTS

Using these command:

```
curl -sL https://raw.githubusercontent.com/tsuru/now/master/run.bash | bash
```

**Comment by andrewsmedina** [comment]
@fellipeh this problem is caused by some problems on "gandanf" (git permission manager) configuration. But I can't reproduce this bug running "now" on aws. 

Can you retry?

**Comment by fellipeh** [comment]
Same problem... :(

Here is the last log:

```
Cloning into 'tsuru-dashboard'...
remote: Counting objects: 10839, done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 10839 (delta 50), reused 0 (delta 0), pack-reused 10731
Receiving objects: 100% (10839/10839), 10.11 MiB | 3.31 MiB/s, done.
Resolving deltas: 100% (6233/6233), done.
Checking connectivity... done.
~/tsuru-dashboard ~ ~
HEAD is now at a61449c fix parsing durations with more than one hour
Already up-to-date.
Warning: Permanently added '172.31.3.60' (ECDSA) to the list of known hosts.
Counting objects: 10716, done.
Compressing objects: 100% (3880/3880), done.
Writing objects: 100% (10716/10716), 10.07 MiB | 0 bytes/s, done.
Total 10716 (delta 6134), reused 10711 (delta 6130)
remote: HEAD is now at a61449c... fix parsing durations with more than one hour
remote: 2016/05/06 18:12:32 Post http://52.67.2.194:8080/apps/tsuru-dashboard/units/register: dial tcp 52.67.2.194:8080: i/o timeout
remote: Exit status 1
To git@172.31.3.60:tsuru-dashboard.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@172.31.3.60:tsuru-dashboard.git'
```

**Comment by mousavian** [comment]
@fellipeh To fix this issue, you can either delete `~git/.bash_profile` file or purge it.

--
@andrewsmedina I think the reason of getting `remote: You must provide a valid Authorization header ` error is that the exiting token in `~git/.bash_profile` is not valid anymore.
to replicate that error you can manually modify `TSURU_TOKEN` in that file and run `now.bash` again; the error will raise at [git push](https://github.com/tsuru/now/blob/c2d34fa2b0cc54ce386d62f5018cc7cab05f2c70/run.bash#L460) 

Mu assumption of causing this error is executing `now.bash` multiple times. So in some circumstances the previous token gets invalidated and needs to be renewed. Is there any way to verify the validity of existing token during installation?

**Comment by ArxdSilva** [comment]
Hi @mousavian and @fellipeh, we are deprecating now script in favor of [tsuru installer](https://docs.tsuru.io/stable/experimental/installer.html) (it's yet with experimental status in docs, but it's well tested and will be the recommended way soon)

Please try Tsuru Installer and let we now your impressions. We have a [recent article about installing Tsuru with installer in google cloud platform](https://blog.tsuru.io/tsuru-paas-on-google-cloud-platform-21640abb4386)

If you want to run Tsuru in your mac without using VM, take a look at our [docker-compose.yml](https://github.com/tsuru/tsuru/blob/master/docker-compose.yml), it's used for dev environment but you can change to run Tsuru images directly. more info: https://docs.tsuru.io/master/contributing/index.html#development-environment

**Comment by mousavian** [comment]
Cool @ArxdSilva, sure will give it a try.
thanks. 👍
