### ISSUE TITLE
Install not working on Xenial

### ISSUE THREAD

**Issue by fnzv** [tsuru/now#46]
curl -sL https://raw.githubusercontent.com/tsuru/now/master/run.bash | bash
...
..
Err:3 http://ppa.launchpad.net/tsuru/ppa/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:4 http://ppa.launchpad.net/tsuru/ppa/ubuntu xenial/main all Packages
Ign:5 http://ppa.launchpad.net/tsuru/ppa/ubuntu xenial/main Translation-en
Reading package lists... Done                      
W: The repository 'http://ppa.launchpad.net/tsuru/ppa/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/tsuru/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead

Needs some repos?

**Comment by andrewsmedina** [comment]
we need to add deb packages for xenial in the tsuru ppa.

**Comment by morpheu** [comment]
We already have xenial packages
