### ISSUE TITLE
Erro ao tentar instalar o tsusu/now

### ISSUE THREAD

**Issue by thiagonego** [tsuru/now#47]
Senhores, instalei o tsuru outras vezes com sucesso. Porém agora não estou conseguindo de forma alguma. Tentei via vagrand, now e seguindo todos os passos. Todos sem sucesso.

O principal erro é quando o script vai fazer o push da aplicação tsuru-dashboard e é rejeitado.

Estou suspeitando que esse erro esteja acontecendo depois da atualizaçao do docker para versão 1.12. Alguém pode me ajudar por favor? 

Segue informações do erro e no final as informações do meu ambiente.

### Mensagem de erro:

```
root@docker-server2:~/tsuru-dashboard# git push tsuru master
Counting objects: 12080, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4272/4272), done.
Writing objects: 100% (12080/12080), 13.02 MiB | 0 bytes/s, done.
Total 12080 (delta 7082), reused 12080 (delta 7082)
remote: HEAD is now at d9e51e7... bump to 0.4.0-rc1
remote: Error in scheduler after previous errors (unable to start node containers: multiple errors: [node containers] failed to create container in http://127.0.0.1:2375 [pierpool]: API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
remote: ) trying to create container: error in scheduler: No nodes found with one of the following metadata: pool=pierpool
To git@192.168.10.201:tsuru-dashboard.git
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@192.168.10.201:tsuru-dashboard.git'
```

### Ambiente

 ```
Servidor: Ubuntu Server 14.04
Comando executado: curl -sL https://raw.githubusercontent.com/tsuru/now/master/run.bash | bash
```

**Comment by andrewsmedina** [comment]
Olá @thiagonego, qual versão de tsuru você está usando? Apenas a versão 1.1 ou do master funcionam corretamente com o Docker 1.12.

**Comment by thiagonego** [comment]
Andrew, estamos usando o script da master. Confere? 

Enviado do meu iPhone

**Comment by andrewsmedina** [comment]
O "now" do master instala o tsuru stable que é o 1.0. Você pode usar o "-N" para pegar o nightly: https://github.com/tsuru/now/blob/master/run.bash#L852

**Comment by thiagonego** [comment]
Andrew, executei o script com o parâmetro -N conforme você indicou. Porém só obtive sucesso quando apontei no script a variável `private_id` para o meu IP privado.

Porém no final, quando chamo a aplicação tsuru-dashboard no browser, nenhum css, js ou imagem é carregada. Retorna um erro 404. Você sabe dizer o real motivo disso?

### Sugestão:
Que tal essa variável `private_ip` ser um parâmetro de entrada do script?

**Comment by thiagonego** [comment]
Andrew, instalando a tar 0.3.0 do tsuru-dashboard funcionou blz... Muito obrigado!
