### ISSUE TITLE
Waiting for docker...

### ISSUE THREAD

**Issue by cerdiogenes** [tsuru/now#49]
I'm using Ubuntu 16.04 and when I run the script I get the following:

``` bash
Waiting for docker...
Waiting for docker...
Waiting for docker...
Error: Couldn't find docker port, please check /var/log/upstart/docker.log for more information
/var/log/upstart/docker.log contents:
cat: /var/log/upstart/docker.log: Arquivo ou diretório não encontrado
```

I'd take a look at the script and find that it's use netstat to detect the running application and in my machine docker is running, but it's not listed in netstat. Here is the output of ps:

``` bash
⋊> ~ ps ax | grep docker                                                                                                                  16:26:46
 8108 ?        Ssl    0:00 /usr/bin/dockerd -H fd://
 8115 ?        Ssl    0:00 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc
 9007 pts/2    S+     0:00 grep --color=auto docker
```

And here is the output of netstat:

``` bash
⋊> ~ sudo netstat -tnlp                                                                                                                   16:26:49
Conexões Internet Ativas (somente servidores)
Proto Recv-Q Send-Q Endereço Local          Endereço Remoto         Estado       PID/Program name
tcp        0      0 127.0.0.1:4381          0.0.0.0:*               OUÇA       2804/spotify    
tcp        0      0 127.0.0.1:4371          0.0.0.0:*               OUÇA       2804/spotify    
tcp        0      0 127.0.0.1:30900         0.0.0.0:*               OUÇA       849/core        
tcp        0      0 0.0.0.0:51413           0.0.0.0:*               OUÇA       3389/transmission-g
tcp        0      0 0.0.0.0:57621           0.0.0.0:*               OUÇA       2804/spotify    
tcp        0      0 127.0.1.1:53            0.0.0.0:*               OUÇA       1155/dnsmasq    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               OUÇA       20702/cupsd     
tcp6       0      0 :::51413                :::*                    OUÇA       3389/transmission-g
tcp6       0      0 ::1:631                 :::*                    OUÇA       20702/cupsd
```

What I am missing?

**Comment by andrewsmedina** [comment]
`now` works fine on ubuntu 14.04. To works with 16.04 we must change it to customize the `Docker` systemd confs instead `/etc/default/docker`

**Comment by tarsisazevedo** [comment]
@cerdiogenes we have a new (experimental) way to setup a tsuru enviroment.
If you want to give it a try, please install tsuru client from master and run `tsuru install`
https://docs.tsuru.io/stable/experimental/installer.html

**Comment by cerdiogenes** [comment]
Thanks! I already have a vagrant machine too, feel free to close this.

Em qui, 13 de out de 2016 às 14:46, Tarsis Azevedo <notifications@github.com>
escreveu:

**Comment by tarsisazevedo** [comment]
Thanks :)

**Comment by andrewsmedina** [comment]
Even with `tsuru install` as a replacement for `now`, `now` should works with ubuntu 16.04 because it is used as tsuru default iaas user-data script.

**Comment by pedrosnk** [comment]
This is an issue with docker installation on ubuntu 16.04 https://github.com/docker/docker/issues/9889#issuecomment-109766580 

Once it's a think possible to be handle bu `now`. It's a temporary fix.

**Comment by guilhermebr** [comment]
I created this PR #54 to solve this problem.

Worked fine with Debian 8.

**Comment by guilhermebr** [comment]
Also tested in Ubuntu 16.06 with systemd:

```
$ ./run.bash --systemd 
Detect Ubuntu 16.04 (xenial), supported system
...
docker found running at 127.0.0.1:2375
...
```

**Comment by andrewsmedina** [comment]
@guilhermebr it would be nice if the `now` script detect automatically if the distro uses systemd

**Comment by guilhermebr** [comment]
@andrewsmedina I made this first, but there's no consensus about the better way to do this... 
I will make a PR with one way that seems better

**Comment by guilhermebr** [comment]
@andrewsmedina PTAL #55
