### ISSUE TITLE
Error when try to install

### ISSUE THREAD

**Issue by HudsonAfonso** [tsuru/now#50]
~ ⚡ $ curl -sL https://raw.githubusercontent.com/tsuru/now/master/run.bash | bash
bash: line 39: wheezy: unbound variable
(23) Failed writing body

**Comment by andrewsmedina** [comment]
@HudsonAfonso what linux distro are you using?

**Comment by HudsonAfonso** [comment]
Darwin MacBook-Pro.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

**Comment by HudsonAfonso** [comment]
news?

**Comment by guilhermebr** [comment]
Hi @HudsonAfonso we are deprecating now script in favor of [tsuru installer](https://docs.tsuru.io/stable/experimental/installer.html) (it's yet with experimental status in docs, but it's well tested and will be the recommended way soon)

Please try Tsuru Installer and let we now your impressions.
We have a [recent article about installing Tsuru with installer in google cloud platform](https://blog.tsuru.io/tsuru-paas-on-google-cloud-platform-21640abb4386)

If you want to run Tsuru in your mac without using VM, tale a look at our [docker-compose.yml](https://github.com/tsuru/tsuru/blob/master/docker-compose.yml), it's used for dev environment but you can change to run Tsuru images directly. more info: https://docs.tsuru.io/master/contributing/index.html#development-environment

[]s
