### ISSUE TITLE
Error instaling on AWS

### ISSUE THREAD

**Issue by webmutation** [tsuru/now#62]
Reading package lists... Done
E: Unable to locate package linux-image-extra-4.4.0-1013-aws
E: Couldn't find any package by glob 'linux-image-extra-4.4.0-1013-aws'
E: Couldn't find any package by regex 'linux-image-extra-4.4.0-1013-aws'

**Comment by cleiton-tavares** [comment]
me too!

**Comment by ArxdSilva** [comment]
@cleiton-tavares and @webmutation , could you guys try to use [tsuru installer](https://docs.tsuru.io/master/experimental/installer.html)? We'll be depreacting `now` package soon.
